### PR TITLE
Include python inside distribution

### PR DESCRIPTION
**Pull request by sevilS**
The build process will generate a package inside dist folder with the following distribution:
**ANDROID**
omvll_ndk_r25c.so
Python-3.10.7 (folder)
sample-omvll-config.py

**iOS**
omvll_xcode_14.dylib
Python-3.10.7 (folder)
sample-omvll-config.py

### CODE REVIEW

**Comment by marcobrador** [comment]
I see this strongly related to #23 - should we combine both?

**Comment by sevilS** [comment]
> I see this strongly related to #23 - should we combine both?

Not sure, this #23 is something related to the tests itself, isn't it? this is more related to the distrib package

**Comment by antoniofrighetto** [comment]
We should only need the Python standard library, not the entire tarball.

**Comment by sevilS** [comment]
> We should only need the Python standard library, not the entire tarball.

I know, but it does not makes much sense to strip the Python package, as it is an entire dependency which has the Lib folder, it makes life of our users easier as they will only replace the entire package and that's it

**Review by antoniofrighetto — APPROVED** [review]
Looks good, thanks! See if @weliveindetail has any feedback to provide, otherwise I'll merge it.

**Comment by weliveindetail** [comment]
LGTM!

My only note would be, that the version of the Python stdlib here must match the version you are linking statically at build-time: https://github.com/open-obfuscator/o-mvll/blob/02d6067a7f8986afb3b34d02c182c2fc235a2a72/src/CMakeLists.txt#L26 I guess it could be enforced in CMake with something like `Python3 3.10 EXACT`. Even better might be to put the stdlib into the deps package as well. If both artifacts come from one source, it's more obvious that they are version-locked.

**Pull request merged**
